- name: create directory
  file: path=/var/www/{{http_host}} state=directory

- name: install the latest version of apache2 web server
  apt:
    name: apache2
    state: latest
    update_cache: yes
    cache_valid_time: 7200
  notify: reload apache2 web server
  tags: apache_package

- name: Set up Apache virtuahHost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: Copy the html page
  template:
    src: "files/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"

- name: change directory and sub dir ownership
  file:
    path: "/var/www/{{http_host}}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755
    recurse: yes

- name: auto start apache2 during bootup
  service: name=apache2 enabled=yes
  tags: apache_conf

- name: enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify: reload apache2 web server
  tags: apache_conf

- name: listen on port 8080 when started the service
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen {{ apache_default_http_port }}"
    line: "Listen {{ apache_custom_http_port }}"
    state: present
    mode: "0644"
  notify: reload apache2 web server
  tags: apache_conf

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: reload apache2 web server

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: reload apache2 web server

- name: make sure apache2 is runninng
  service: name=apache2 state="{{ apache_state }}"

- name: check if you can connect to this localhost:8080 and get status code 200 if succeddeed
  uri:
    url: "http://localhost:8080"
  register: content

- debug: var=content

- name: print kernel info
  include_role:
    name: ../common
    tasks_from: kernel_output.yml
  
